#ifndef SCHEDULER_TESTS_H_INCLUDED
#define SCHEDULER_TESTS_H_INCLUDED

void test_scheduler_setup(void);
void test_scheduler_tear_down(void);

void test_actualizar_un_pcb_por_bloqueo_actualiza_estimacion_actual(void);
void test_actualizar_un_pcb_por_bloqueo_actualiza_real_anterior_como_sumatoria_de_reales_ejecutados_hasta_ahora(void);
void test_actualizar_un_pcb_por_bloqueo_actualiza_reales_ejecutados_hasta_ahora_en_cero(void);
void test_actualizar_un_pcb_por_desalojo_actualiza_reales_ejecutados_hasta_ahora(void);
void test_actualizar_un_pcb_por_desalojo_no_actualiza_estimacion_actual(void);
void test_actualizar_un_pcb_por_varios_desalojos_actualiza_reales_ejecutados_hasta_ahora_como_la_sumatoria(void);
void test_actualizar_un_pcb_por_varios_desalojos_disminuye_rafaga_restante(void);
void test_empates_en_srt_degradan_en_un_fifo(void);
void test_planificar_segun_fifo(void);

#endif
